// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieAppInClass.Services;

#nullable disable

namespace MovieAppInClass.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20250131172023_InitialAndMovieEntity")]
    partial class InitialAndMovieEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieAppInClass.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Ratting")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movie");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ratting = 5,
                            Title = "Annie Hall",
                            Year = 1977
                        },
                        new
                        {
                            Id = 2,
                            Ratting = 4,
                            Title = "Apocalypse Now",
                            Year = 1979
                        },
                        new
                        {
                            Id = 3,
                            Ratting = 5,
                            Title = "Casablanca",
                            Year = 1942
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
